[package]
name = "cesride"
version = "0.1.3"
edition = "2021"
description = "Cryptographic primitives for use with Composable Event Streaming Representation (CESR)"
license = "Apache-2.0"
keywords = ["cesr", "keri", "acdc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "~0.21"
blake2 = "~0.10"
blake3 = "~1"
ed25519-dalek = "~1"
k256 = "~0.12"
lazy_static = "~1"
sha2 = "~0.10"
sha3 = "~0.10"
thiserror = "~1"
# Clippy fix: disable "oldtime" feature for chrono
chrono = { version = "~0.4", default-features = false, features = ["clock"] }

[dev-dependencies]
hex-literal = "*"
hex = "*"
rand = "0.7.0" # this needs pinning for one of the seeding pieces of a signing suite
rand_core = "*"
rstest = "*"
